pool:
  vmImage: 'windows-latest'

steps:

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true


- task: PowerPlatformExportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'POWERAPPS-PRE-SDS-SBOX'
    SolutionName: 'dts_pre_recorded_evidence'
    SolutionOutputFile: 'dts_pre_recorded_evidence.zip'
    AsyncOperation: false

- task: PowerPlatformUnpackSolution@0
  inputs:
    SolutionInputFile: 'dts_pre_recorded_evidence.zip'
    SolutionTargetFolder: 'dts_pre_recorded_evidence'

- task: CmdLine@2
  inputs:
    script: |
      echo Commit Power Platform Solution
      git config user.email "prebuildpipeline@hmcts.net"
      git config user.name "PRE Build Pipeline"
      git checkout -b dev
      git pull origin
      git add --all
      git commit -m "Automatic solution commit"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin dev
