---
name: PRE Solution Exporter
trigger: none
pr: none
parameters:
  - name: serviceConnection
    displayName: Import from Service Connection
    type: string
    default: 'POWERAPPS-PRE-SDS-SBOX'
    values:
     # - 'POWERAPPS-PRE-SBOX'
      - 'POWERAPPS-PRE-SDS-SBOX'
      - 'POWERAPPS-PRE-SDS-DEV'
      - 'POWERAPPS-PRE-SDS-STG'
      - 'POWERAPPS-PRE-SDS-PROD'
  - name: exportToBranch
    displayName: Export To Branch
    type: string
    default: 'dev'

variables:
  solutionName: dts_pre_recorded_evidence

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self
  persistCredentials: true
  clean: true

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true

- task: PowerPlatformExportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: ${{ parameters.serviceConnection }}
    SolutionName: $(solutionName)
    SolutionOutputFile: 'dts_pre_recorded_evidence.zip'
    AsyncOperation: false
    Managed: false
    MaxAsyncWaitTime: 120
    ExportAutoNumberingSettings: true
    ExportCalendarSettings: true
    ExportCustomizationSettings: true
    ExportEmailTrackingSettings: true
    ExportGeneralSettings: true
    ExportIsvConfig: true
    ExportMarketingSettings: true
    ExportOutlookSynchronizationSettings: true
    ExportRelationshipRoles: true
# - task: PowerPlatformChecker@0
  displayName: 'Power Platform solution Checker '
  inputs:
    PowerPlatformSPN: ${{ parameters.serviceConnection }}
    RuleSet: '0ad12346-e108-40b8-a956-9a8f95ea18c9'
- task: PowerPlatformUnpackSolution@0
  inputs:
    SolutionInputFile: 'dts_pre_recorded_evidence.zip'
    SolutionTargetFolder: 'src'

- task: CmdLine@2
  inputs:
    script: |
      echo Commit Power Platform Solution
      git config user.email "prebuildpipeline@hmcts.net"
      git config user.name "PRE Build Pipeline"
      git pull origin master
      git checkout -b ${{ parameters.exportToBranch }}
      git add --all
      git commit -m "Automatic solution commit"
      git -c http.extraheader="AUTHORIZATION: bearer $(system.githubPat)" push origin ${{ parameters.exportToBranch }}
