pool:
  vmImage: 'windows-latest'

steps:

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true


- task: PowerPlatformExportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'POWERAPPS-PRE-SDS-SBOX'
    SolutionName: 'dts_pre_recorded_evidence'
    SolutionOutputFile: 'dts_pre_recorded_evidence.zip'
    AsyncOperation: false

- task: PowerPlatformUnpackSolution@0
  inputs:
    SolutionInputFile: 'dts_pre_recorded_evidence.zip'
    SolutionTargetFolder: 'dts_pre_recorded_evidence'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'POWERAPPS-PRE-SBOX'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az devops login --organization https://dev.azure.com/hmcts/
      az artifacts universal publish \
          --organization https://dev.azure.com/hmcts/ \
          --project="Pre-Recorded Evidence" \
          --scope project \
          --feed dts-pre-artifacts \
          --name my-first-package \
          --version 0.0.1 \
          --description "Welcome to Universal Packages" \
          --path .

          #- task: CmdLine@2
          #  inputs:
          #    script: |
          #      echo Commit Power Platform Solution
          #      git config user.email "prebuildpipeline@hmcts.net"
          #      git config user.name "PRE Build Pipeline"
          #      git checkout -b dev
          #      git pull origin
          #      git add --all
          #      git commit -m "Automatic solution commit"
          #      git -c http.extraheader="AUTHORIZATION: bearer $(system.githubPat)" push origin dev
