---
name: PRE Solution Exporter
trigger: none
pr: none
variables:
  serviceConnection: 'POWERAPPS-PRE-SDS-SBOX'
  solutionName: dts_pre_recorded_evidence


pool:
  vmImage: 'windows-latest'

steps:

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true


- task: PowerPlatformExportSolution@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: $(serviceConnection)
    SolutionName: $(solutionName)
    SolutionOutputFile: 'dts_pre_recorded_evidence.zip'
    AsyncOperation: false

- task: PowerPlatformUnpackSolution@0
  inputs:
    SolutionInputFile: 'dts_pre_recorded_evidence.zip'
    SolutionTargetFolder: 'dts_pre_recorded_evidence'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: 'dts_pre_recorded_evidence.zip'
#     artifactName: drop

- task: CmdLine@2
  inputs:
    script: |
      echo Commit Power Platform Solution
      git config user.email "prebuildpipeline@hmcts.net"
      git config user.name "PRE Build Pipeline"
      git checkout -b dev
      git pull origin
      git add --all
      git commit -m "Automatic solution commit"
      git -c http.extraheader="AUTHORIZATION: bearer $(system.githubPat)" push origin dev
