---
name: PRE Solution Deployment
trigger: none
pr: none
parameters:
  - name: serviceConnection
    displayName: Deploy to Service Connection
    type: string
    default: 'POWERAPPS-PRE-SDS-SBOX'
    values:
      - 'POWERAPPS-PRE-SDS-SBOX'
  - name: deployFromBranch
    displayName: Deploy From Branch
    type: string
    default: 'master'

variables:
  solutionName: dts_pre_recorded_evidence

pool:
  vmImage: 'windows-latest'

steps:

- checkout: self
  persistCredentials: true
  clean: true

- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true

- task: CmdLine@2
  inputs:
    script: |
      echo Deploy Power Platform Solution
      git config user.email "prebuildpipeline@hmcts.net"
      git config user.name "PRE Build Pipeline"
      git checkout ${{ parameters.deployFromBranch }}

- task: PowerPlatformPackSolution@0
  inputs:
    SolutionSourceFolder: 'src'
    SolutionOutputFile: 'dts_pre_recorded_evidence'

#- task: PowerPlatformCreateEnvironment@0
#  inputs:
#    authenticationType: 'PowerPlatformSPN'
#    PowerPlatformSPN: 'POWERAPPS-PRE-SDS-SBOX'
#    DisplayName: 'PRE Sandbox'
#    EnvironmentSku: 'Sandbox'
#    LocationName: 'unitedkingdom'
#    LanguageName: '1033'
#    CurrencyName: 'GBP'
#    DomainName: 'pre-sandbox'
