name: PRE portal export from sandbox
trigger: none
pool:
  vmImage: windows-latest
variables:
  - group: auth-sbox
parameters:
  - name: serviceConnection
    displayName: Use environment Service Connection
    type: string
    default: 'POWERAPPS-PRE-SDS-SBOX'
    values:
      - 'POWERAPPS-PRE-SDS-SBOX'
      - 'POWERAPPS-PRE-SDS-DEV'
      - 'POWERAPPS-PRE-SDS-STG'
      - 'POWERAPPS-PRE-SDS-PROD'
  - name: exportToBranch
    displayName: Export To Branch
    type: string
    default: 'dev'

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest https://aka.ms/PowerAppsCLI -OutFile pac.msi
        msiexec /i pac.msi /quiet /norestart

  - task: PowerShell@2
    condition: and(succeeded(), eq('${{ parameters.exportToBranch }}', 'dev'))
    env:
      PacAuthProfileName: ${{ parameters.serviceConnection }}
    inputs:
      targetType: 'inline'
      script: |
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        pac install latest
        pac auth create --name $(PacAuthProfileName) `
          --url $(portalinstanceurl) `
          --tenant $(PowerPlatformAadDirectoryId) `
          --applicationId $(PowerPlatformAadApplicationId) `
          --clientSecret $(PowerPlatformAadApplicationSecret)
        pac org who
        pac auth select --name $(PacAuthProfileName)
        pac paportal download -o true --path $(System.DefaultWorkingDirectory)/src/portal -id ${portalid}

  - task: CmdLine@2
    condition: and(succeeded(), eq('${{ parameters.exportToBranch }}', 'dev'))
    inputs:
      script: |
        echo Commit Power Platform Solution
        git config user.email "prebuildpipeline@hmcts.net"
        git config user.name "PRE Build Pipeline"
        git pull origin master
        git checkout -b ${{ parameters.exportToBranch }}
        git add --all
        git commit -m "Automatic solution commit"
        git -c http.extraheader="AUTHORIZATION: bearer $(system.githubPat)" push origin ${{ parameters.exportToBranch }}
